logging:
  level:
    root: INFO
    kafka.*: WARN
    org.springframework.data: DEBUG
    org.springframework.*: INFO
    org.apache.kafka.*: WARN


server:
  port: 8050

base:
  keycloak-uri: http://localhost:9090/auth

spring:
  application:
    name: profile-service
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: reactive-profile-service
      auto-index-creation: true
  cloud:
    stream:
      bindings:
        output:
          binder: kafka
          destination: follow
          contentType: 'application/json'
          group: follow-group
      kafka:
        binder:
          brokers:
            - localhost:9092
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${base.keycloak-uri}/realms/jhipster/.well-known/openid-configuration
      client:
        provider:
          oidc:
            issuer-uri: ${base.keycloak-uri}/realms/jhipster
        registration:
          oidc:
            client-id: web_app
            client-secret: web_app
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false

follow:
  messaging:
    timeout: 30000
