logging:
  level:
    root: INFO
    kafka.*: WARN
    org.springframework.*: INFO
    org.apache.kafka.*: WARN

server:
  port: 8090

base:
  keycloak-uri: http://localhost:9090/auth

spring:
  application:
    name: comment-service
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: reactive-comment-service
  cloud:
    stream:
      bindings:
        article:
          binder: kafka
          destination: article
          group: article-group
          contentType: 'application/json'
          consumer:
            concurrency: 1
      kafka:
        binder:
          brokers:
            - localhost:9092
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${base.keycloak-uri}/realms/jhipster/.well-known/openid-configuration
      client:
        provider:
          oidc:
            issuer-uri: ${base.keycloak-uri}/realms/jhipster
        registration:
          oidc:
            client-id: web_app
            client-secret: web_app

spring-docs:
  title: Comment-Service API
  description:
  version: 0.0.1
  contact-name:
  contact-url:
  contact-email:
  license: unlicensed
  license-url:
  servers:
