logging:
  level:
    root: INFO
    kafka.*: WARN
    org.springframework.*: INFO
    org.apache.kafka.*: WARN

server:
  port: 8050

spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: reactive-user-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9090/auth/realms/jhipster/.well-known/openid-configuration
      client:
        provider:
          oidc:
            issuer-uri: http://localhost:9090/auth/realms/jhipster
        registration:
          oidc:
            client-id: web_app
            client-secret: web_app

jwt:
  authenticated-path-matchers:
    - "/api/**"
  identity-claim-label: clientId
