logging:
  level:
    root: INFO
    org.springframework.data: DEBUG
    org.springframework.*: INFO

server:
  port: 8040

base:
  keycloak-uri: http://localhost:9090/auth

spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: reactive-user-service
      auto-index-creation: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${base.keycloak-uri}/realms/jhipster/.well-known/openid-configuration
      client:
        provider:
          oidc:
            issuer-uri: ${base.keycloak-uri}/realms/jhipster
        registration:
          oidc:
            client-id: web_app
            client-secret: web_app
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
