logging:
  level:
    root: INFO
    kafka.*: WARN
    org.springframework.data: DEBUG
    org.springframework.*: INFO
    org.apache.kafka.*: WARN

server:
  port: 8060

base:
  keycloak-uri: http://localhost:9090/auth

spring:
  application:
    name: feed-service
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: reactive-feed-service
      auto-index-creation: true
  cloud:
    stream:
      bindings:
        article:
          binder: kafka
          destination: article
          group: article-group
          contentType: 'application/json'
          consumer:
            concurrency: 1
        favourite:
          binder: kafka
          destination: favourite
          group: favourite-group
          contentType: 'application/json'
            consumer:
              concurrency: 1
        follow:
          binder: kafka
          destination: follow
          group: follow-group
          contentType: 'application/json'
            consumer:
              concurrency: 1
      kafka:
        binder:
          brokers:
            - localhost:9092
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${base.keycloak-uri}/realms/jhipster/.well-known/openid-configuration
      client:
        provider:
          oidc:
            issuer-uri: ${base.keycloak-uri}/realms/jhipster
        registration:
          oidc:
            client-id: web_app
            client-secret: web_app
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
