logging:
  level:
    root: INFO
    kafka.*: WARN
    org.springframework.*: INFO
    org.apache.kafka.*: WARN

server:
  port: 8060

spring:
  application:
    name: feed-service
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: reactive-feed-service
