logging:
  level:
    root: INFO
    kafka.*: WARN
    org.springframework.*: INFO
    org.apache.kafka.*: WARN

server:
  port: 8060

base:
  keycloak-uri: http://localhost:9090/auth

spring:
  application:
    name: feed-service
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: reactive-feed-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${base.keycloak-uri}/realms/jhipster/.well-known/openid-configuration
      client:
        provider:
          oidc:
            issuer-uri: ${base.keycloak-uri}/realms/jhipster
        registration:
          oidc:
            client-id: web_app
            client-secret: web_app
