logging:
  level:
    root: INFO
    org.springframework.*: INFO

server:
  port: 8040

base:
  keycloak-uri: http://localhost:9090/auth

spring:
  application:
    name: keycloak-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${base.keycloak-uri}/realms/jhipster/.well-known/openid-configuration
      client:
        provider:
          oidc:
            issuer-uri: ${base.keycloak-uri}/realms/jhipster
          manager:
            token-uri: ${base.keycloak-uri}/realms/jhipster/protocol/openid-connect/token
        registration:
          oidc:
            client-id: web_app
            client-secret: web_app
          manager:
            authorization-grant-type: client_credentials
            client-id: client-app
            client-secret: 3c83fcb4-167a-4788-9e6d-5e459543087d
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false

keycloak:
  uri: http://localhost:9090/auth/admin/realms/jhipster
