logging:
  level:
    root: INFO
    kafka.*: WARN
    org.springframework.*: INFO
    org.apache.kafka.*: WARN

server:
  port: 8080

base:
  keycloak-uri: http://localhost:9090/auth

spring:
  application:
    name: article-service
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: reactive-articles-service
  cloud:
    stream:
      bindings:
        output:
          binder: kafka
          destination: article
          contentType: 'application/json'
          group: article-group
      kafka:
        binder:
          brokers:
            - localhost:9092
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${base.keycloak-uri}/realms/jhipster/.well-known/openid-configuration
      client:
        provider:
          oidc:
            issuer-uri: ${base.keycloak-uri}/realms/jhipster
        registration:
          oidc:
            client-id: web_app
            client-secret: web_app

article:
  messaging:
    timeout: 30000
